name: cam_flutter

description: Camera streaming server and viewer in Flutter/Dart
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  path_provider: ^2.1.1
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  google_mlkit_face_detection: ^0.11.0
  image: ^4.1.3
  file_picker: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/bin/ffmpeg.exe
